#
# Application configuration for integration testing
#

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:test"
    username: SA
    password:
  jta:
    bitronix:
      properties:
        server-id: "datac-testing"
        journal: "null"
  jpa:
    show-sql: true

datac:
  fileDirectory: "work-test"